#!/usr/bin/env node

/**
 * Comprehensive Bridge System Health Check
 * Final verification of all bridge components
 * 
 * Generated by @bridges-agent
 * Date: January 8, 2026 (Final Check)
 */

import { readFile, readdir } from 'fs/promises';
import { join } from 'path';

console.log('🔍 COMPREHENSIVE BRIDGE SYSTEM HEALTH CHECK');
console.log('============================================\n');

async function checkFileExists(path) {
  try {
    await readFile(path, 'utf8');
    return true;
  } catch (e) {
    return false;
  }
}

async function analyzeFile(path, expectedFeatures = []) {
  try {
    const content = await readFile(path, 'utf8');
    const analysis = {
      exists: true,
      size: content.length,
      lines: content.split('\n').length,
      features_found: expectedFeatures.filter(feature => content.includes(feature)),
      has_error_handling: content.includes('try') && content.includes('catch'),
      has_logging: content.includes('console.log') || content.includes('console.error'),
      exports_handler: content.includes('export default') && content.includes('handler'),
      health_score: 0
    };
    
    // Calculate health score
    let score = 50; // Base score for existing
    if (analysis.exports_handler) score += 20;
    if (analysis.has_error_handling) score += 15;
    if (analysis.has_logging) score += 10;
    if (analysis.features_found.length > expectedFeatures.length * 0.7) score += 15;
    
    analysis.health_score = Math.min(100, score);
    return analysis;
  } catch (e) {
    return {
      exists: false,
      error: e.message,
      health_score: 0
    };
  }
}

async function main() {
  const healthReport = {
    timestamp: new Date().toISOString(),
    bridges: {},
    infrastructure: {},
    overall_health: 0,
    status: 'unknown'
  };

  // Check main webhook endpoints
  const bridges = {
    'x.js': ['webhook', 'signature', 'CRC', 'POST', 'GET', 'tweet_create_events', 'direct_message_events'],
    'discord.js': ['webhook', 'signature', 'MESSAGE_CREATE', 'GUILD_MEMBER', 'INTERACTION_CREATE'],
    'github.js': ['webhook', 'signature', 'push', 'pull_request', 'issues'],
    'farcaster.js': ['webhook', 'cast', 'reaction', 'mention'],
    'whatsapp.js': ['webhook', 'message', 'status', 'business'],
    'telegram/webhook.js': ['webhook', 'message', 'command', 'inline']
  };

  console.log('📡 CHECKING WEBHOOK ENDPOINTS');
  console.log('─────────────────────────────\n');

  for (const [filename, expectedFeatures] of Object.entries(bridges)) {
    const paths = [
      join('api/webhooks', filename),
      join('api', filename)
    ];
    
    let analysis = null;
    for (const path of paths) {
      analysis = await analyzeFile(path, expectedFeatures);
      if (analysis.exists) break;
    }
    
    const platform = filename.replace('.js', '').replace('/webhook', '');
    healthReport.bridges[platform] = analysis;
    
    const status = analysis.health_score >= 80 ? '✅' : 
                  analysis.health_score >= 60 ? '⚠️' : 
                  analysis.exists ? '❌' : '❓';
    
    console.log(`${status} ${platform.toUpperCase()}`);
    console.log(`   Health: ${analysis.health_score}%`);
    console.log(`   Features: ${analysis.features_found?.length || 0}/${expectedFeatures.length}`);
    if (analysis.exists) {
      console.log(`   Size: ${Math.round(analysis.size / 1024)}KB, Lines: ${analysis.lines}`);
    }
    console.log();
  }

  // Check infrastructure components
  console.log('🔧 CHECKING INFRASTRUCTURE');
  console.log('──────────────────────────\n');

  const infrastructure = {
    'status.js': ['configuration', 'statistics', 'health', 'webhook_urls'],
    'health.js': ['bridges', 'storage', 'configured'],
    'test.js': ['test', 'endpoint', 'verify']
  };

  for (const [filename, expectedFeatures] of Object.entries(infrastructure)) {
    const path = join('api/webhooks', filename);
    const analysis = await analyzeFile(path, expectedFeatures);
    
    healthReport.infrastructure[filename.replace('.js', '')] = analysis;
    
    const status = analysis.health_score >= 80 ? '✅' : 
                  analysis.health_score >= 60 ? '⚠️' : 
                  analysis.exists ? '❌' : '❓';
    
    console.log(`${status} ${filename.toUpperCase()}`);
    console.log(`   Health: ${analysis.health_score}%`);
    console.log(`   Features: ${analysis.features_found?.length || 0}/${expectedFeatures.length}`);
    console.log();
  }

  // Check webhook directories
  console.log('📁 CHECKING DIRECTORY STRUCTURE');
  console.log('────────────────────────────────\n');

  try {
    const webhooksDir = await readdir('api/webhooks');
    console.log('✅ WEBHOOK DIRECTORY EXISTS');
    console.log(`   Files: ${webhooksDir.length}`);
    console.log(`   Contents: ${webhooksDir.join(', ')}`);
    console.log();
    
    healthReport.infrastructure.directory_structure = {
      exists: true,
      file_count: webhooksDir.length,
      files: webhooksDir,
      health_score: 90
    };
  } catch (e) {
    console.log('❌ WEBHOOK DIRECTORY MISSING');
    healthReport.infrastructure.directory_structure = {
      exists: false,
      error: e.message,
      health_score: 0
    };
  }

  // Calculate overall health
  const allComponents = [
    ...Object.values(healthReport.bridges),
    ...Object.values(healthReport.infrastructure)
  ];
  
  const totalScore = allComponents.reduce((sum, comp) => sum + (comp.health_score || 0), 0);
  const avgScore = totalScore / allComponents.length;
  
  healthReport.overall_health = Math.round(avgScore);
  
  if (avgScore >= 90) {
    healthReport.status = 'excellent';
  } else if (avgScore >= 75) {
    healthReport.status = 'healthy';
  } else if (avgScore >= 50) {
    healthReport.status = 'degraded';
  } else {
    healthReport.status = 'critical';
  }

  // Generate summary
  console.log('📊 HEALTH SUMMARY');
  console.log('─────────────────\n');
  
  const bridgeCount = Object.values(healthReport.bridges).filter(b => b.exists && b.health_score >= 70).length;
  const totalBridges = Object.keys(healthReport.bridges).length;
  
  console.log(`🎯 Overall Health: ${healthReport.overall_health}% (${healthReport.status.toUpperCase()})`);
  console.log(`🌉 Working Bridges: ${bridgeCount}/${totalBridges}`);
  console.log(`🔧 Infrastructure: ${Object.values(healthReport.infrastructure).filter(i => i.health_score >= 70).length}/4 components healthy`);
  console.log();

  // Recommendations
  console.log('💡 RECOMMENDATIONS');
  console.log('──────────────────\n');

  if (healthReport.overall_health >= 90) {
    console.log('✅ Bridge system is EXCELLENT - ready for production');
    console.log('🎯 Focus on: Configuration, testing, monitoring');
  } else if (healthReport.overall_health >= 75) {
    console.log('✅ Bridge system is HEALTHY - mostly operational');
    console.log('🔧 Focus on: Fix any degraded components');
  } else {
    console.log('⚠️  Bridge system needs attention');
    console.log('🛠️  Focus on: Rebuild failed components');
  }

  // Check for common issues
  const issues = [];
  if (!healthReport.infrastructure.status?.exists) {
    issues.push('Missing status endpoint');
  }
  if (!healthReport.infrastructure.health?.exists) {
    issues.push('Missing health endpoint');
  }
  if (bridgeCount < 3) {
    issues.push('Less than 3 bridges operational');
  }

  if (issues.length > 0) {
    console.log('\n⚠️  ISSUES FOUND:');
    issues.forEach(issue => console.log(`   - ${issue}`));
  } else {
    console.log('\n🎉 NO CRITICAL ISSUES FOUND!');
  }

  console.log('\n' + '='.repeat(50));
  console.log(`🏁 FINAL STATUS: ${healthReport.status.toUpperCase()} (${healthReport.overall_health}%)`);
  console.log('='.repeat(50));

  return healthReport;
}

// Run the health check
main().then(report => {
  // Could save report to file or send to monitoring system
  console.log('\n✅ Health check completed successfully!');
}).catch(error => {
  console.error('❌ Health check failed:', error);
  process.exit(1);
});